Repository yiisoft/yii2-httpclient, pull requests merged in 2019-04, with the labels that each got.

#174 Add MockTransport for test environments
  CHANGELOG.md
  docs/guide/usage-transports.md
  src/MockTransport.php
  tests/MockTransportTest.php
Labels: type:docs, type:test

#179 Closes #178. Fix failed test.
  tests/RequestTest.php
Labels: type:test

#181 Closes #149. Fix type error when creating response with headers param…
  CHANGELOG.md
  src/StreamTransport.php
  tests/ClientTest.php
Labels: status:ready for merge

#180 Closes #171. Add "Content-Length: 0" header when sending request with…
  CHANGELOG.md
  src/CurlTransport.php
  src/UrlEncodedFormatter.php
  tests/CurlTransportTest.php
  tests/UrlEncodedFormatterTest.php
Labels: status:ready for merge

#182 Closes #66. Add CURLOPT_FILE option support
  CHANGELOG.md
  docs/guide/basic-usage.md
  src/CurlTransport.php
  src/Request.php
  tests/CurlTransportTest.php
Labels: status:ready for merge

#185 Add CurlFormatter in order to support CURLFile for uploading files
  CHANGELOG.md
  docs/guide/basic-usage.md
  src/Client.php
  src/CurlFormatter.php
  src/CurlTransport.php
  tests/CurlFormatterTest.php
Labels: type:enhancement

#186 Closes #167. Add support for multiple params with the same name.
  CHANGELOG.md
  src/Message.php
  src/Request.php
  tests/RequestTest.php
Labels: status:under development

#187 Unit tests.
  phpunit.xml.dist
  src/Client.php
  src/Response.php
  tests/ClientTest.php
  tests/CurlTransportTest.php
  tests/MessageTest.php
  tests/RequestTest.php
  tests/ResponseTest.php
  tests/XmlFormatterTest.php
  tests/XmlParserTest.php
  tests/test_file.txt
Labels: type:test
